complexity:
  active: true
  LargeClass:
    active: true
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  NestedBlockDepth:
    active: false
  ComplexMethod:
    active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

exceptions:
  active: true
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  ThrowingExceptionInMain:
    active: true
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  EnumNaming:
    enumEntryPattern: '[A-Z0-9_]+'

potential-bugs:
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
  LateinitUsage:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  NullableToStringCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnreachableCatchBlock:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true
  ImplicitDefaultLocale:
    active: false

style:
  ForbiddenComment:
    active: false
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  # Us using mutable data classes gives us the benefit of the generated stuff whilst also keeping allocations down
  DataClassShouldBeImmutable:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: true
    maxDestructuringEntries: 5
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenMethodCall:
    active: true
  ForbiddenVoid:
    active: true
  MagicNumber:
    active: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreNamedArgument: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreAnnotation: true
    ignoreNumbers: ["-3", "-2", "-1", "-0.5", "0", "0.5", "1", "2", "3", "64", "90", "180", "360"]
    excludes: ["**/test/**"]
  MandatoryBracesIfStatements:
    active: false
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    active: false
    excludeCommentStatements: true
  NoTabs:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: true
    max: 4
    excludeGuardClauses: true
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: true
    max: 4
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckNotNull:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseIsNullOrEmpty:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
  NewLineAtEndOfFile:
    active: false